---
# possibly saved as tasks/foo.yml

- debug:
    msg: "HELLLLLLLLLLLLOOOOOOO"

#
- name: create Organisation
  uri:
    url: http://localhost:8080/aa-restapi/ca/advancedauth/v1/admin/orgs
    return_content: yes
    method: POST
    body: "{{imported_var}}"
    status_code: 201
    body_format: json
    headers:
      Content-Type: "application/json"
      accept: "application/json"
      authToken: "{{token}}"

  register: result
