---
- name: Create Organisation to set risk and strong auth profile.
  hosts: localhost

  tasks:

     - debug:
         msg: " Token create org {{token}}"

     - name: create Organisation
       uri:
         url: http://localhost:8080/aa-restapi/ca/advancedauth/v1/admin/orgs
         return_content: yes
         method: POST
         body: "{{ lookup('file','aaProfiles/createOrg.json') }}"
         status_code: 201
         body_format: json
         
       register: result
       
     - debug:
         msg: "Web Service Response {{result.json}} " 
         
