---
- name: get Auth Token.
  hosts: localhost

  tasks:

     - name: get auth token
       uri:
         url: http://localhost:8080/aa-restapi/ca/advancedauth/v1/admin/authtoken
         return_content: yes
         method: POST
         body: "{{ lookup('file','aaProfiles/getAuthToken.json') }}"
         status_code: 201         
         body_format: json

       register: result

     - debug:
         msg: "Web Service Response {{result.json.authToken}} "

     - set_fact:
         token: "{{result.json.authToken}}"

     - debug:
         msg: "Token {{token}}"
