---
# possibly saved as tasks/foo.yml

- debug:
    msg: " ******create****** {{venki.stdout}}"

- name: placeholder foo
  debug:
    msg: "Venki Alahari {{orgName}}"

- name: create Organisation
  uri:
    url: http://localhost:8080/aa-restapi/ca/advancedauth/v1/admin/orgs
    return_content: yes
    method: POST
    body: "{{orgName}}"
    status_code: 201
    body_format: json

  register: result
