---
# tasks file for aaprofilepublish


#- name: Read JSON file (can also be a variable).
#  shell: cat ./orgs.json
#  register: json


- debug :
    msg: "Hello Venki {{json_file}}  {{result}} "



- name: Get simple value.
  set_fact:
  myvar: "{{ json.stdout | from_json }}"

- debug:
    msg: "Alahari  {{ json_file |  json_query('[0].orgName') }}  here "


- debug:
    msg: " {{simple_value}}"

- debug:
    msg: >
         --== Ansible Jinja2 for range

         {% for entry in json_file -%}
            {{ entry }} {{ "VVVVVVVVVVVV" }}

         {% endfor %}

- name: Iteratae JSON
  debug: var=item.orgName
  with_items: "{{json_file}}"

- shell: echo "Venki"
  register: venki

- debug:
    msg: " ************ {{venkiAlahari.stdout}}"
- include: tasks/createOrg.yml
    orgName={{item}}
  with_items: "{{json_file}}"
