---
# possibly saved as tasks/foo.yml

- debug:
    msg: "Getting name from main playbook {{repoPassword}}"


- name: get Organisations
  uri:
    url: https://devgtw.primericaonline.com/aa-restapi/ca/advancedauth/v1/admin/orgs
    return_content: yes
    method: GET
    status_code: 200
    body_format: json
    headers:
      Content-Type: "application/json"
      accept: "application/json"
      authToken: "{{token}}"

  register: result


- debug:
    msg: "RESULTS {{result}}"

 # - name: Get the Advanced Auth configs from github
