---
# tasks file for aaprofilepublish


#- name: Read JSON file (can also be a variable).
#  shell: cat ./orgs.json
#  register: json



- include: tasks/getOrg.yml

# - script: tasks/gitrepo.sh

- name: get repo
  shell: |
    git clone https://github.com/alahari/aaProfiles.git

- debug:
    msg: " json format ........ {{result | to_nice_json(indent=2)}}"



- name: Ansible create file with content example
  copy:
    dest: "aaProfiles/org.json"
    content: |
      {{ result.content | from_json | to_nice_json(indent=2)}}

# - script: tasks/gitpublish.sh


- name: change dir
  command: chdir=/mnt/c/work/advancedAuthProfManager ls



# - script: tasks/gitpublish.sh

# - name: git checkout
#   command: git checkout master

- name: Run git commands
  shell: |
    cd aaProfiles/
    git add *
    git commit -a -m "latest changes in dev"
    git push  https://alahari:{{repoPassword}}@github.com/alahari/aaProfiles.git

- name: Clean artifact path
  file:
    state: absent
    path: "aaProfiles/"

# - name: git add
#   command: git add *
#
# - name: git commit
#   command: git commit -a -m "latest changes in dev"
#
# - name: git push
#   command: git push  https://alahari:Veda2018@github.com/alahari/aaProfiles.git
